#!/bin/bash

# Goto src directory
cd $HOME/os161/src;
# Configure the ostree path
./configure

# Config the VM option
cd ./kern/conf/
# modify config file when necessary
./config ASST3
cd ../compile/ASST3/
#bmake clean

# build dependencies and install
bmake clean
bmake -j8 depend
bmake -j8
bmake -j8 install
# Modify the sys.conf file when necessary
# Especially the ramsize and cpus 
# bmake -h when you modify userland
# Launch the compiled kernel
cd $HOME/os161/src/
sleep 2
bmake -j8
bmake -j8 install 
