#!/bin/bash

# Goto src directory
cd $HOME/os161/src;
# Configure the ostree path
./configure

# Config the VM option
cd ./kern/conf/
# modify config file when necessary
./config DUMBVM
cd ../compile/DUMBVM/
#bmake clean

# build dependencies and install
bmake clean
bmake depend
bmake
bmake install
# Modify the sys.conf file when necessary
# Especially the ramsize and cpus 
# bmake -h when you modify userland
# Launch the compiled kernel
cd $HOME/os161/root/
